apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  labels:
    {{- include "hello-devops.labels" . | nindent 4 }}

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  ENV: {{ .Values.config.environment | quote }}
